Add missing httpx dev dependency (#12)
* Refactor endpoint for flatter structure

* Remove urllib3 from explicit dependencies

* Switch from fastapi[standard] to fastapi

* Add test_tahoe module

* Refactor endpoint to use dependency injection

* Add index_post_data test

* Add index_post_cap_string_happy test

* Add project description and usage instructions to Readme

* Add missing httpx dev dependency

I couldn't run the tests without adding httpx first, a transitive dependency:
> RuntimeError: The starlette.testclient module requires the httpx package to be installed.

---------

Co-authored-by: JW Jacobson <116485484+jwjacobson@users.noreply.github.com>