Refactor a little, add tests,  update readme (#9)
* Refactor endpoint for flatter structure

* Remove urllib3 from explicit dependencies

* Switch from fastapi[standard] to fastapi

* Add test_tahoe module

* Refactor endpoint to use dependency injection

* Add index_post_data test

* Add index_post_cap_string_happy test

* Add project description and usage instructions to Readme

* Add missing python-multipart dependency

Following the `README.md` and running `uv run fastapi dev src/api/main.py` in the `jeff-dev` branch gives me

```
RuntimeError: Form data requires "python-multipart" to be installed.
You can install "python-multipart" with:

pip install python-multipart
```

This change makes it so that the `uv sync` step installs python-multipart.

---------

Co-authored-by: Florian Sesser <florian@leastauthority.com>